### ISSUE TITLE
sqlite3 problem

### ISSUE THREAD

**Issue by agn-7** [wbh1/grafana-sqlite-to-postgres#14]
Hello
 
I had a problem during importing a `grafana.db` to postgresql:

```
./grafana-migrate_linux grafana.db "postgres://grafana_usr:xxxx@172.17.0.1:5432/grafana_db?sslmode=disable"
```

Out:

```
INFO[2020-06-14T16:24:45+04:30] 📁 SQLlite file: grafana.db                   
INFO[2020-06-14T16:24:45+04:30] 📁 Dump directory: /tmp                       
FATAL[2020-06-14T16:24:45+04:30] ❌ exec: "sqlite3": executable file not found in $PATH - is the sqlite3 command line tool installed?
```

Also, I've done these installations before:

```
sudo apt-get install gcc
go get -u github.com/mattn/go-sqlite3
go install github.com/mattn/go-sqlite3
```

---
[*NOTE*]:

 - golang version: 1.14
 - OS: Ubuntu 16.04

**Comment by wbh1** [comment]
Hi Benyamin,

You have to have sqlite installed on the machine that you're running this tool on. That's why the error message mentions the "command line tool". When you install sqlite, it out to include an executable called "sqlite3".

https://www.sqlitetutorial.net/download-install-sqlite/

**Comment by agn-7** [comment]
Thanks for the response, but as I mentioned in my question, I've installed `sqlite3` by these commands below:

```
go get -u github.com/mattn/go-sqlite3
go install github.com/mattn/go-sqlite3
```

**Comment by wbh1** [comment]
Those just install the sqlite driver that can be used by the `database/sql` golang [package](https://golang.org/pkg/database/sql/). You actually need to install the sqlite command line tools from the sqlite project located [here](https://sqlite.org/download.html)

**Comment by agn-7** [comment]
Thank you. But the mentioned link didn't work for me. Instead, I used the following command and the problem was solved:

```
sudo apt-get install sqlite3
```
