### ISSUE TITLE
Add file extension to Windows version

### ISSUE THREAD

**Issue by yosiasz** [wbh1/grafana-sqlite-to-postgres#31]
Greetings

Is the windows version supposed to be an exe or msi?

Thanks for tool!

**Comment by wbh1** [comment]
It is an `.exe`. Thank you for pointing out that it doesn't have the extension on the release page!

I'll convert this issue to track adding that in.

**Comment by wbh1** [comment]
Fixed in 68bad93236ecf83f19652ab2d78d86da442368b8
