### ISSUE TITLE
error on grafana 9.0.3 db

### ISSUE THREAD

**Issue by yosiasz** [wbh1/grafana-sqlite-to-postgres#32]
Greetings,

I am getting the following error

![image](https://user-images.githubusercontent.com/900951/186742357-86650c76-41a6-467f-833b-4e327eb929a0.png)

**Comment by rmartinez3** [comment]
super late post. but that showed up on my end since I did not start graafana prior hand to have it setup needed tables.

Though when I tried script on my end . I did notice issues. Though not sure if its postgres version or grafana version related

**Comment by wbh1** [comment]
Basically what @rmartinez3 said - this is generally an indication that you did not start an instance of Grafana connected to your destination Postgres database prior to running the migration tool, which is required to pre-create the tables.

I'm going to open a new issue to track efforts to make this more obvious and seamless by reducing/eliminating the need for manual steps, though.
