### ISSUE TITLE
Bug in Dockerfile

### ISSUE THREAD

**Issue by FStefanni** [wbh1/grafana-sqlite-to-postgres#45]
Hi,

if i currently build by using the provided Dockerfile by using:
```bash
DOCKER_BUILDKIT=1 docker build --tag:migrator:1.0.0 .
```
Then the entry point is wrong, since it points to `grafana-migrate`, instead of `grafana-migrate/tags/v2.2.3-3-gfde745d`.

To fix, just replace the `COPY` command with the following:

```
COPY --from=builder /go/src/github.com/wbh1/grafana-sqlite-to-postgres/dist/grafana-migrate_linux*/tags/* ./grafana-migrate
```

Regards

**Comment by wbh1** [comment]
Fixed in d7b0c69534a6b82bf16ead7483e36b04afe90363.

Thanks!
